// js/fees.js - Fees & Payments Logic
import { pb, connected } from './core/pocketbase.js';
import { toast } from './ui/toasts.js';
import { initNotifications } from './notifications.js';

// 🔒 HIDE ADMIN LINK FOR NON-ADMINS
const sessionRaw = localStorage.getItem('uzima_session');
if (sessionRaw) {
    try {
        const auth = JSON.parse(sessionRaw);
        // If role is NOT admin, hide the Admin sidebar link
        if (auth.model?.role !== 'admin') {
            const adminLink = document.querySelector('a[href="admin.html"]');
            if (adminLink) adminLink.style.display = 'none';
        }
    } catch (e) {}
}

const FEES_KEY = 'uzima_fees_data';
const initialData = {
  totalTuition: 85000,
  transactions: [
    { id: 't1', date: '2025-09-15', ref: 'MPESA9X2K1', desc: 'Tuition Installment 1', amount: 25000, status: 'paid' },
    { id: 't2', date: '2025-11-02', ref: 'BANK88L2M9', desc: 'Library & Lab Fees', amount: 8500, status: 'paid' },
    { id: 't3', date: '2026-01-10', ref: 'PENDING001', desc: 'Tuition Installment 2', amount: 25000, status: 'pending' }
  ]
};

function loadData() {
  const stored = localStorage.getItem(FEES_KEY);
  if (stored) return JSON.parse(stored);
  localStorage.setItem(FEES_KEY, JSON.stringify(initialData));
  return initialData;
}

function saveData(data) { localStorage.setItem(FEES_KEY, JSON.stringify(data)); }
function formatCurrency(amount) { return 'KES ' + amount.toLocaleString(); }

function updateBalanceUI(data) {
  const paid = data.transactions.filter(t => t.status === 'paid').reduce((sum, t) => sum + t.amount, 0);
  const pending = data.transactions.filter(t => t.status === 'pending').reduce((sum, t) => sum + t.amount, 0);
  const due = data.totalTuition - paid;
  document.getElementById('totalDue').textContent = formatCurrency(Math.max(0, due));
  document.getElementById('totalPaid').textContent = formatCurrency(paid);
  document.getElementById('totalPending').textContent = formatCurrency(pending);
  const nextPending = data.transactions.find(t => t.status === 'pending');
  document.getElementById('nextDueDate').textContent = nextPending ? nextPending.date : 'None';
}

function renderTransactions(data) {
  const tbody = document.getElementById('transactionsBody');
  if (data.transactions.length === 0) {
    tbody.innerHTML = '<tr><td colspan="5" style="text-align:center;color:var(--t4)">No transactions yet</td></tr>'; return;
  }
  tbody.innerHTML = data.transactions.sort((a,b) => new Date(b.date) - new Date(a.date)).map(t => `
    <tr>
      <td>${t.date}</td>
      <td><code style="background:var(--bg);padding:2px 6px;border-radius:4px;">${t.ref}</code></td>
      <td>${t.desc}</td>
      <td>${formatCurrency(t.amount)}</td>
      <td><span class="status-badge status-${t.status}">${t.status}</span></td>
    </tr>
  `).join('');
}

function downloadReceipt(data) {
  const paid = data.transactions.filter(t => t.status === 'paid');
  const totalPaid = paid.reduce((s, t) => s + t.amount, 0);
  const student = JSON.parse(localStorage.getItem('uzima_session') || '{}').model;
  const name = student.name?.name || student.name || 'Student';
  const sid = student.name?.sid || student.sid || 'N/A';

  let receipt = `UZIMA UNIVERSITY - PAYMENT RECEIPT\n========================================\nStudent: ${name}\nID: ${sid}\nDate: ${new Date().toLocaleDateString()}\n\nPAID TRANSACTIONS:\n`;
  paid.forEach(t => { receipt += `- ${t.date} | ${t.ref} | ${t.desc} | ${formatCurrency(t.amount)}\n`; });
  receipt += `\nTOTAL PAID: ${formatCurrency(totalPaid)}\nREMAINING BALANCE: ${formatCurrency(Math.max(0, data.totalTuition - totalPaid))}\n========================================\nGenerated by Uzima Portal`;

  const blob = new Blob([receipt], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = `Uzima_Receipt_${sid}_${new Date().toISOString().split('T')[0]}.txt`;
  a.click(); URL.revokeObjectURL(url);
  toast.show('Receipt downloaded', 's');
}

document.addEventListener('DOMContentLoaded', () => {
  // 🔒 ROLE GUARD: Block parents from student/admin pages
  const sessionRaw = localStorage.getItem('uzima_session');
  if (sessionRaw) {
    try {
      const auth = JSON.parse(sessionRaw);
      const role = auth.model?.role?.toLowerCase().trim() || 'student';
      if (role === 'parent') {
        console.log('🚫 Parent access blocked. Redirecting to parent.html');
        window.location.href = 'parent.html';
        return; // ⚠️ Stops the rest of the page from loading
      }
    } catch (e) { /* ignore parse errors */ }
  }
  
  const raw = localStorage.getItem('uzima_session');
  if (!raw) { window.location.href = 'index.html'; return; }
  const auth = JSON.parse(raw);
  if (Date.now() > auth.expires) { localStorage.removeItem('uzima_session'); window.location.href = 'index.html'; return; }

  const user = auth.model;
  const navName = document.getElementById('navName');
  const navAvatar = document.getElementById('navAvatar');
  if (navName) navName.textContent = (user.name?.name || user.name || 'User').split(' ')[0];
  if (navAvatar) navAvatar.textContent = (user.name?.name || user.name || 'U').charAt(0).toUpperCase();

  const navProfile = document.getElementById('navProfile');
  const dropdown = document.getElementById('profileDropdown');
  if (navProfile && dropdown) {
    navProfile.addEventListener('click', e => { e.stopPropagation(); dropdown.classList.toggle('show'); });
    document.addEventListener('click', () => dropdown.classList.remove('show'));
  }
  document.getElementById('logoutBtn').onclick = () => {
    if (connected && pb) pb.authStore.clear();
    localStorage.removeItem('uzima_session');
    window.location.href = 'index.html';
  };

  const data = loadData();
  updateBalanceUI(data);
  renderTransactions(data);

  document.getElementById('payNowBtn').onclick = () => {
    document.getElementById('paymentForm').reset();
    document.getElementById('payAmount').value = data.transactions.find(t => t.status === 'pending')?.amount || '';
    document.getElementById('paymentModal').classList.add('open');
  };
  document.getElementById('downloadInvoiceBtn').onclick = () => downloadReceipt(data);

  document.getElementById('paymentForm').addEventListener('submit', (e) => {
    e.preventDefault();
    const amount = parseInt(document.getElementById('payAmount').value);
    const ref = document.getElementById('payRef').value;
    const method = document.getElementById('payMethod').value;
    if (!amount || !ref) return;

    const newTx = { id: 't' + Date.now(), date: new Date().toISOString().split('T')[0], ref: ref.toUpperCase(), desc: `Tuition Payment (${method.toUpperCase()})`, amount: amount, status: 'paid' };
    data.transactions.push(newTx);
    saveData(data);
    closeModal('paymentModal');
    updateBalanceUI(data);
    renderTransactions(data);
    toast.show('Payment recorded successfully', 's');
  });
  
  // Initialize Notifications
  initNotifications();
});

window.closeModal = (id) => document.getElementById(id).classList.remove('open');